# Generated by Django 5.1.7 on 2025-03-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DentalClinicServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cavity_filling', models.BooleanField(default=False, verbose_name='Cavity Filling')),
                ('root_canal', models.BooleanField(default=False, verbose_name='Root Canal')),
                ('tooth_extraction', models.BooleanField(default=False, verbose_name='Tooth Extraction')),
                ('gum_treatment', models.BooleanField(default=False, verbose_name='Gum Treatment')),
                ('teeth_whitening', models.BooleanField(default=False, verbose_name='Teeth Whitening')),
                ('laminates', models.BooleanField(default=False, verbose_name='Laminates')),
                ('composite', models.BooleanField(default=False, verbose_name='Composite')),
                ('smile_design', models.BooleanField(default=False, verbose_name='Smile Design')),
                ('implants', models.BooleanField(default=False, verbose_name='Dental Implants')),
                ('dental_prosthetics', models.BooleanField(default=False, verbose_name='Dental Prosthetics')),
                ('crown_and_bridges', models.BooleanField(default=False, verbose_name='Crowns and Bridges')),
                ('fixed_orthodontics', models.BooleanField(default=False, verbose_name='Fixed Orthodontics')),
                ('removable_orthodontics', models.BooleanField(default=False, verbose_name='Removable Orthodontics')),
                ('scaling_and_polishing', models.BooleanField(default=False, verbose_name='Scaling and Polishing')),
                ('fluoride_therapy', models.BooleanField(default=False, verbose_name='Fluoride Therapy')),
                ('sealants', models.BooleanField(default=False, verbose_name='Sealants')),
                ('online_consultation', models.BooleanField(default=False, verbose_name='Online Consultation')),
                ('appointment_reminders', models.BooleanField(default=False, verbose_name='Appointment Reminders')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('patient_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('previous_treatments', models.TextField(blank=True, null=True)),
                ('image_file', models.ImageField(upload_to='radiology_images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Patient Record',
            },
        ),
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('available_date', models.DateField(verbose_name='Available Date')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='DentalApp.dentalclinicservices')),
            ],
        ),
    ]
