# Generated by Django 5.1.7 on 2025-03-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentalApp', '0002_remove_patientrecord_image_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='serviceschedule',
            name='service',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='description',
        ),
        migrations.DeleteModel(
            name='DentalClinicServices',
        ),
        migrations.DeleteModel(
            name='ServiceSchedule',
        ),
    ]
