# Generated by Django 5.1.7 on 2025-03-28 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentalApp', '0003_mymodel_remove_serviceschedule_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalClinicServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cavity_filling', models.BooleanField(default=False, verbose_name='Cavity Filling')),
                ('root_canal', models.BooleanField(default=False, verbose_name='Root Canal')),
                ('tooth_extraction', models.BooleanField(default=False, verbose_name='Tooth Extraction')),
                ('gum_treatment', models.BooleanField(default=False, verbose_name='Gum Treatment')),
                ('teeth_whitening', models.BooleanField(default=False, verbose_name='Teeth Whitening')),
                ('laminates', models.BooleanField(default=False, verbose_name='Laminates')),
                ('composite', models.BooleanField(default=False, verbose_name='Composite')),
                ('smile_design', models.BooleanField(default=False, verbose_name='Smile Design')),
                ('implants', models.BooleanField(default=False, verbose_name='Dental Implants')),
                ('dental_prosthetics', models.BooleanField(default=False, verbose_name='Dental Prosthetics')),
                ('crown_and_bridges', models.BooleanField(default=False, verbose_name='Crowns and Bridges')),
                ('fixed_orthodontics', models.BooleanField(default=False, verbose_name='Fixed Orthodontics')),
                ('removable_orthodontics', models.BooleanField(default=False, verbose_name='Removable Orthodontics')),
                ('scaling_and_polishing', models.BooleanField(default=False, verbose_name='Scaling and Polishing')),
                ('fluoride_therapy', models.BooleanField(default=False, verbose_name='Fluoride Therapy')),
                ('sealants', models.BooleanField(default=False, verbose_name='Sealants')),
                ('online_consultation', models.BooleanField(default=False, verbose_name='Online Consultation')),
                ('appointment_reminders', models.BooleanField(default=False, verbose_name='Appointment Reminders')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DentalApp.patientrecord')),
            ],
        ),
    ]
