# Generated by Django 5.1.7 on 2025-03-30 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentalApp', '0004_dentalclinicservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentalclinicservices',
            name='id',
        ),
        migrations.AlterField(
            model_name='dentalclinicservices',
            name='Patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DentalApp.patientrecord'),
        ),
    ]
