# Generated by Django 5.1.7 on 2025-03-30 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentalApp', '0005_remove_dentalclinicservices_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalclinicservices',
            name='service_id',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dentalclinicservices',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DentalApp.patientrecord'),
        ),
    ]
